package pt.utl.ist.meic.geofriendsfire.fragments;

import android.content.Context;
import android.support.v4.app.Fragment;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import com.firebase.geofire.GeoFire;
import com.firebase.geofire.GeoLocation;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.text.SimpleDateFormat;
import java.util.Date;

import butterknife.BindView;
import butterknife.ButterKnife;
import butterknife.OnClick;
import pt.utl.ist.meic.geofriendsfire.MyApplicationContext;
import pt.utl.ist.meic.geofriendsfire.R;
import pt.utl.ist.meic.geofriendsfire.activities.DrawerMainActivity;
import pt.utl.ist.meic.geofriendsfire.location.GPSTracker;
import pt.utl.ist.meic.geofriendsfire.models.Event;

public class CreateEventFragment extends Fragment {


    private static final String EVENTS_REF = "/events";
    private static final String EVENTS_LOCATIONS_REF = "/eventsLocations";

    @BindView(R.id.categorySpinner)
    Spinner eventCategory;

    @BindView(R.id.eventDescription)
    TextView eventDescription;

    private DatabaseReference mDatabase;


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        super.onCreateView(inflater, container, savedInstanceState);
        View view = inflater.inflate(R.layout.fragment_create_event, container, false);
        mDatabase = FirebaseDatabase.getInstance().getReference();
        ButterKnife.bind(this,view);
        return view;
    }

    @OnClick(R.id.createEventButton)
    public void createNewEventButtonClicked() {

        GPSTracker mGpsTracker = new GPSTracker(getContext());

        if (!mGpsTracker.canGetLocation()) {
            Toast.makeText(getContext(), "can not get location", Toast.LENGTH_LONG).show();
        }else if(eventDescription.getText().toString().trim().isEmpty()){
            Toast.makeText(getContext(), "plz provide an event description", Toast.LENGTH_SHORT).show();
        }
        else {
            double latitude = mGpsTracker.getLatitude();
            double longitude = mGpsTracker.getLongitude();
            String category = String.valueOf(eventCategory.getSelectedItem());
            String description = eventDescription.getText().toString().trim();

            SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
            String creationDate = df.format(new Date());

            String myId = ((MyApplicationContext)getContext().getApplicationContext()).getFirebaseUser().getUid();
            String myName = ((MyApplicationContext)getContext().getApplicationContext()).getFirebaseUser().getDisplayName();

            Event newEvent = new Event(myId,myName,description ,category,creationDate);

            // Generate a reference to a new location and add some data using push()
            DatabaseReference eventsRef = mDatabase.child(EVENTS_REF);
            DatabaseReference newEventRef = eventsRef.push();

            // Add some data to the new location
            newEventRef.setValue(newEvent.toMap());

            // Get the unique ID generated by push()
            String eventID = newEventRef.getKey();

            //create geoLocation for the event - key is the event ID
            DatabaseReference ref = mDatabase.child(EVENTS_LOCATIONS_REF);
            GeoFire geoFire = new GeoFire(ref);
            geoFire.setLocation(eventID, new GeoLocation(latitude, longitude));

            ((DrawerMainActivity)getContext()).setupViewPagerEvents();
        }
    }
}
